name: Execute Python

on:
  workflow_dispatch:

jobs:
  setup-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
           token: ${{ secrets.GIT_PAT }}

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Execute Python code
        run: python3 python-file.py

      - name: print files
        run: ls
      - name: Find the files which will be uploaded to s3
        run: |
           mkdir s3-upload-files
           find . -type f -name "datafile*" | xargs -I {} cp {} s3-upload-files/
           ls
           cd s3-upload-files
           ls
      - name: Find the files which are recuring files
        run: |
            month=$(date +"%-m")
            echo "$month"
            mkdir recuring-files-1
            find . -type f -name "$month*" | xargs -I {} cp {} recuring-files-1/
            ls
            cd recuring-files
            ls
      - name: Upload the recuring files to github
        run: |
           git config user.name "rohansarkar1998"
           git config user.email "rohan.mili.98@gamil.com"
           git add recuring-files-1 || true
           git commit -m "Pushing code to github"
           git push origin main
           
            
